### ISSUE TITLE
플러그인 업데이트시 에러 strpos() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by darron1217** [xpressengine/xpressengine#1003]
안녕하세요 xe3를 예전부터 지켜보던 사람입니다

베타버전도 나오고 해서 설치해봤는데, 플러그인 업데이트시 아래와 같은 에러가 납니다

어디서 잘못된건지 감이 오지 않아서 질문드립니다
```
[2019-06-13 23:14:45] production.ERROR: strpos() expects parameter 1 to be string, array given {"userId":"3471a3f2-45c6-4245-810a-ebf932a396ba","email":"darron1217@gmail.com","exception":"[object] (ErrorException(code: 0): strpos() expects parameter 1 to be string, array given at /workspace/xe3/app/Console/Commands/PluginCommand.php:281)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'strpos() expect...', '/workspace/xe3/...', 281, Array)
#1 /workspace/xe3/app/Console/Commands/PluginCommand.php(281): strpos(Array, ':')
#2 /workspace/xe3/app/Console/Commands/PluginUpdate.php(127): App\\Console\\Commands\\PluginCommand->parse(Array)
#3 /workspace/xe3/app/Console/Commands/PluginUpdate.php(51): App\\Console\\Commands\\PluginUpdate->getPluginData(Array)
#4 [internal function]: App\\Console\\Commands\\PluginUpdate->handle()
#5 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#6 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Xpressengine\\Foundation\\Application), Array, Object(Closure))
#8 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Xpressengine\\Foundation\\Application), Array, Array, NULL)
#9 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#10 /workspace/xe3/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#11 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#12 /workspace/xe3/app/Console/Commands/ShouldOperation.php(85): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\StreamOutput))
#13 /workspace/xe3/app/Console/Commands/PluginCommand.php(75): App\\Console\\Commands\\ShouldOperation->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\StreamOutput))
#14 /workspace/xe3/vendor/symfony/console/Application.php(969): App\\Console\\Commands\\PluginCommand->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\StreamOutput))
#15 /workspace/xe3/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\PluginUpdate), Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\StreamOutput))
#16 /workspace/xe3/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\StreamOutput))
#17 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\StreamOutput))
#18 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Console/Application.php(177): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\StreamOutput))
#19 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(249): Illuminate\\Console\\Application->call('plugin:update', Object(Illuminate\\Support\\Collection), Object(Symfony\\Component\\Console\\Output\\StreamOutput))
#20 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Foundation\\Console\\Kernel->call('plugin:update', Array, Object(Symfony\\Component\\Console\\Output\\StreamOutput))
#21 /workspace/xe3/app/Http/Controllers/PluginController.php(307): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#22 [internal function]: App\\Http\\Controllers\\PluginController->App\\Http\\Controllers\\{closure}()
#23 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Object(Closure), Array)
#24 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(75): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Xpressengine\\Foundation\\Application), Object(Closure), Object(Closure))
#26 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Xpressengine\\Foundation\\Application), Object(Closure), Array, NULL)
#27 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(964): Illuminate\\Container\\Container->call(Object(Closure))
#28 /workspace/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(191): Illuminate\\Foundation\\Application->terminate()
#29 /workspace/xe3/index.php(62): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Xpressengine\\Http\\Request), Object(Illuminate\\Http\\RedirectResponse))
#30 {main}
"} 

```

**Comment by darron1217** [comment]
권한 문제였네요 하하 :)

**Comment by smaker** [comment]
@darron1217 어떻게 해결하셨나요? 저도 똑같은 에러가 발생하는 데 해결 방안이 나오지 않아서요.  ㅠ.ㅠ
