### ISSUE TITLE
artisan host 업데이트 시 문제가 있습니다.

### ISSUE THREAD

**Issue by hhgyu** [xpressengine/xpressengine#108]
php artisan site:host:update --siteKey=default --host=xxx

호스트 변경시에 오류가 발생합니다.

```
  [Illuminate\Database\QueryException]                                                                                                                                          
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updatedAt' in 'field list' (SQL: update `xe_site` set `host` = xxx, `updatedAt` = 2016-03-27 17:36:05   
  where `siteKey` = default)                                                                                                                                                    
```

```                                                                              
  [PDOException]                                                                      
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updatedAt' in 'field list' 
```

storage/logs/laravel.log
```
Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updatedAt' in 'field list' (SQL: update `xe_site` set `host` = xxx
, `updatedAt` = 2016-03-27 17:36:05 where `siteKey` = default) in /home/xxx/public_html/xe/vendor/laravel/framework/src/Illuminate/Database/Connection.php:65
1
Stack trace:
#0 /home/xxx/public_html/xe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(611): Illuminate\Database\Connection->runQueryCallback('update `x
e_site...', Array, Object(Closure))
#1 /home/xxx/public_html/xe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\Database\Connection->run('update `xe_site...', A
rray, Object(Closure))
#2 /home/xxx/public_html/xe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(359): Illuminate\Database\Connection->affectingStatement('update
`xe_site...', Array)
#3 /home/xxx/public_html/xe/core/src/Xpressengine/Database/VirtualConnection.php(418): Illuminate\Database\Connection->update('update `xe_site...', Array)
#4 /home/xxx/public_html/xe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1836): Xpressengine\Database\VirtualConnection->update('update
 `xe_site...', Array)
#5 /home/xxx/public_html/xe/core/src/Xpressengine/Database/DynamicQuery.php(289): Illuminate\Database\Query\Builder->update(Array)
#6 /home/xxx/public_html/xe/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(384): Xpressengine\Database\DynamicQuery->update(Array)
#7 /home/xxx/public_html/xe/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1526): Illuminate\Database\Eloquent\Builder->update(Array)
#8 /home/xxx/public_html/xe/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1445): Illuminate\Database\Eloquent\Model->performUpdate(Obje
ct(Xpressengine\Database\Eloquent\Builder), Array)
#9 /home/xxx/public_html/xe/core/src/Xpressengine/Database/Eloquent/DynamicModel.php(302): Illuminate\Database\Eloquent\Model->save(Array)
#10 /home/xxx/public_html/xe/core/src/Xpressengine/Site/SiteHandler.php(268): Xpressengine\Database\Eloquent\DynamicModel->save()
#11 [internal function]: Xpressengine\Site\SiteHandler->put(Object(Xpressengine\Site\Site))
#12 /home/xxx/public_html/xe/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(106): call_user_func_array('parent::put', Array)
#13 [internal function]: Proxy_Xpressengine_Site_SiteHandler->_proxyTargetCall('put', Array)
#14 /home/xxx/public_html/xe/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(90): call_user_func_array(Array, Array)
#15 [internal function]: Proxy_Xpressengine_Site_SiteHandler->Xpressengine\Interception\Proxy\{closure}(Object(Xpressengine\Site\Site))
#16 /home/xxx/public_html/xe/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(94): call_user_func_array(Object(Closure), Array)
#17 [internal function]: Xpressengine\Interception\ProxyInvocationHandler->__invoke(Object(Xpressengine\Site\Site))
#18 /home/xxx/public_html/xe/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(72): call_user_func_array(Object(Xpressengine\Interception\ProxyIn
vocationHandler), Array)
#19 /home/xxx/public_html/xe/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(92): Xpressengine\Interception\ProxyInvocationHandler->callProxy(Array,
Object(Closure))
#20 /home/xxx/public_html/xe/storage/interception/Proxy_Xpressengine_Site_SiteHandler.php(70): Proxy_Xpressengine_Site_SiteHandler->_proxyMethodCall('put', A
rray)
#21 /home/xxx/public_html/xe/app/Console/Commands/Site.php(83): Proxy_Xpressengine_Site_SiteHandler->put(Object(Xpressengine\Site\Site))
#22 [internal function]: App\Console\Commands\Site->handle()
#23 /home/xxx/public_html/xe/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#24 /home/xxx/public_html/xe/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#25 /home/xxx/public_html/xe/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\Argv
Input), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /home/xxx/public_html/xe/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\
Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /home/xxx/public_html/xe/vendor/symfony/console/Application.php(841): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),
Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /home/xxx/public_html/xe/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\Sit
e), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /home/xxx/public_html/xe/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input
\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /home/xxx/public_html/xe/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Sy
mfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /home/xxx/public_html/xe/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Comp
onent\Console\Output\ConsoleOutput))
#32 {main}
```

**Comment by jhyeon1010** [comment]
model 에 timestamp 값이 잘못 설정되어 있었습니다.
해당 부분 수정하였습니다.
