### ISSUE TITLE
(디버깅모드일때) Object of class DateTime could not be converted to string 에러

### ISSUE THREAD

**Issue by darron1217** [xpressengine/xpressengine#1158]
```
[2020-06-03 19:17:54] production.ERROR: Object of class DateTime could not be converted to string {"userId":"4f87cf14-0542-4ed4-a542-212354bfcb04","email":"admin@admin.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Object of class DateTime could not be converted to string at D:\\stormWorkspace\\pottophoto3-web\\app\\Providers\\DatabaseServiceProvider.php:57)
[stacktrace]
#0 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(350): App\\Providers\\DatabaseServiceProvider->App\\Providers\\{closure}()
#1 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(200): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#2 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(825): Illuminate\\Events\\Dispatcher->dispatch()
#3 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(682): Illuminate\\Database\\Connection->event()
#4 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(635): Illuminate\\Database\\Connection->logQuery()
#5 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(459): Illuminate\\Database\\Connection->run()
#6 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(411): Illuminate\\Database\\Connection->statement()
#7 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2142): Illuminate\\Database\\Connection->insert()
#8 D:\\stormWorkspace\\pottophoto3-web\\vendor\\venturecraft\
evisionable\\src\\Venturecraft\\Revisionable\\RevisionableTrait.php(209): Illuminate\\Database\\Query\\Builder->insert()
#9 D:\\stormWorkspace\\pottophoto3-web\\vendor\\venturecraft\
evisionable\\src\\Venturecraft\\Revisionable\\RevisionableTrait.php(77): Soweb\\XePlugin\\SoAcademy\\Models\\Student->postSave()
#10 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(350): Soweb\\XePlugin\\SoAcademy\\Models\\Student::Venturecraft\\Revisionable\\{closure}()
#11 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(200): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#12 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(173): Illuminate\\Events\\Dispatcher->dispatch()
#13 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasEvents.php(148): Illuminate\\Events\\Dispatcher->fire()
#14 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(591): Illuminate\\Database\\Eloquent\\Model->fireModelEvent()
#15 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(562): Illuminate\\Database\\Eloquent\\Model->finishSave()
#16 D:\\stormWorkspace\\pottophoto3-web\\core\\src\\Xpressengine\\Database\\Eloquent\\DynamicModel.php(253): Illuminate\\Database\\Eloquent\\Model->save()
#17 D:\\stormWorkspace\\pottophoto3-web\\privates\\so_academy\\src\\Repositories\\Eloquent\\EloquentStudentRepository.php(72): Xpressengine\\Database\\Eloquent\\DynamicModel->save()
#18 D:\\stormWorkspace\\pottophoto3-web\\privates\\so_academy\\src\\Http\\Controllers\\Api\\StudentController.php(109): Soweb\\XePlugin\\SoAcademy\\Repositories\\Eloquent\\EloquentStudentRepository->update()
#19 [internal function]: Soweb\\XePlugin\\SoAcademy\\Http\\Controllers\\Api\\StudentController->update()
#20 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array()
#21 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#22 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#23 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(169): Illuminate\\Routing\\Route->runController()
#24 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(658): Illuminate\\Routing\\Route->run()
#25 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#26 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#27 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#28 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#30 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#31 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#33 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#34 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#36 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(660): Illuminate\\Pipeline\\Pipeline->then()
#37 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack()
#38 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(601): Illuminate\\Routing\\Router->runRoute()
#39 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute()
#40 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#41 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#42 D:\\stormWorkspace\\pottophoto3-web\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#43 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#44 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 D:\\stormWorkspace\\pottophoto3-web\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#46 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle()
#47 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#49 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#50 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#52 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#53 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#55 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#56 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#58 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#59 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 D:\\stormWorkspace\\pottophoto3-web\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#61 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Fruitcake\\Cors\\HandleCors->handle()
#62 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#64 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#65 D:\\stormWorkspace\\pottophoto3-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#66 D:\\stormWorkspace\\pottophoto3-web\\index.php(57): Illuminate\\Foundation\\Http\\Kernel->handle()
#67 {main}
"} 

```
app.debug = true 일때 모델에 $dates (날짜 Mutator) 가 있으면 에러가 납니다.

원인은 아래 한줄 때문이고
https://github.com/xpressengine/xpressengine/blob/5d09e1a1eace9f3f4006c2e49765c72ff9d3c445/app/Providers/DatabaseServiceProvider.php#L56

string만 바인딩 값으로 넘어오는것이 아니기 때문에 확인이 필요할듯 합니다.

**Comment by akasima** [comment]
#1159 에서 해결된 이슈로 확인되어 닫습니다.
