### ISSUE TITLE
관리자 페이지->설정->관리페이지 권한 설정 클릭시 오류가 발생합니다.

### ISSUE THREAD

**Issue by hhgyu** [xpressengine/xpressengine#116]
관리자 페이지->설정->관리페이지 권한 설정 클릭시 오류가 발생합니다.
http://xxx/settings/setting/permissions

![image](https://cloud.githubusercontent.com/assets/4644504/14225463/8d17ae28-f8fe-11e5-952f-254d62ae44c0.png)

그리고 혹시 저기 사각 검은색은 제가 가린게 아닌데
저렇게 뜨네요..

css는 
```css
html{background:url(../img/bg_admin_snb.gif) 0 0 repeat-y}
html, body,.admin_wrap{position:relative;left:0;right:0;min-height:100%;height:100%;margin:0;padding:0} 
```

의도와는 다르게 표현되는 듯합니다.

```
cms.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to undefined method Xpressengine\Permission\PermissionHandler::make() in /xxx/public_html/resources/UIObjects/Settings/SettingsPermission.php:24
Stack trace:
#0 /xxx/public_html/core/src/Xpressengine/UIObject/helpers.php(35): Xpressengine\UIObjects\Settings\SettingsPermission->render()
#1 /xxx/public_html/storage/framework/views/4a0a89cdd1a99a6dcd0ef1b933a7211c(21): uio('xpressengine@re...', Array)
#2 /xxx/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(42): include('/xxx...')
#3 /xxx/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/xxx...', Array)
#4 /xxx/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/xxx...', Array)
#5 /xxx/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#6 /xxx/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#7 /xxx/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(161): Illuminate\View\View->render()
#8 /xxx/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\View\View->gatherData()
#9 /xxx/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#10 /xxx/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#11 /xxx/public_html/core/src/Xpressengine/Presenter/Html/HtmlRenderer.php(191): Illuminate\View\View->render()
#12 [internal function]: Xpressengine\Presenter\Html\HtmlRenderer->render()
#13 /xxx/public_html/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(106): call_user_func_array('parent::render', Array)
#14 [internal function]: Proxy_Xpressengine_Presenter_Html_HtmlRenderer->_proxyTargetCall('render', Array)
#15 /xxx/public_html/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(90): call_user_func_array(Array, Array)
#16 [internal function]: Proxy_Xpressengine_Presenter_Html_HtmlRenderer->Xpressengine\Interception\Proxy\{closure}()
#17 /xxx/public_html/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(94): call_user_func_array(Object(Closure), Array)
#18 [internal function]: Xpressengine\Interception\ProxyInvocationHandler->__invoke()
#19 /xxx/public_html/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(72): call_user_func_array(Object(Xpressengine\Interception\ProxyInvocationHandler), Array)
#20 /xxx/public_html/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(92): Xpressengine\Interception\ProxyInvocationHandler->callProxy(Array, Object(Closure))
#21 /xxx/public_html/storage/interception/Proxy_Xpressengine_Presenter_Html_HtmlRenderer.php(25): Proxy_Xpressengine_Presenter_Html_HtmlRenderer->_proxyMethodCall('render', Array)
#22 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Proxy_Xpressengine_Presenter_Html_HtmlRenderer->render()
#23 /xxx/public_html/vendor/symfony/http-foundation/Response.php(200): Illuminate\Http\Response->setContent(Object(Proxy_Xpressengine_Presenter_Html_HtmlRenderer))
#24 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1229): Symfony\Component\HttpFoundation\Response->__construct(Object(Proxy_Xpressengine_Presenter_Html_HtmlRenderer))
#25 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\Router->prepareResponse(Object(Xpressengine\Http\Request), Object(Proxy_Xpressengine_Presenter_Html_HtmlRenderer))
#26 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Xpressengine\Http\Request))
#27 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#29 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#30 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\SettingsController), Object(Illuminate\Routing\Route), Object(Xpressengine\Http\Request), 'editPermissions')
#32 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Xpressengine\Http\Request), 'App\\Http\\Contro...', 'editPermissions')
#33 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Xpressengine\Http\Request))
#34 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Xpressengine\Http\Request))
#35 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Xpressengine\Http\Request))
#36 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#37 /xxx/public_html/core/src/Xpressengine/Settings/SettingsMiddleware.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#38 [internal function]: Xpressengine\Settings\SettingsMiddleware->handle(Object(Xpressengine\Http\Request), Object(Closure))
#39 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#41 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#42 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Xpressengine\Http\Request))
#43 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Xpressengine\Http\Request))
#44 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Xpressengine\Http\Request))
#45 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#46 /xxx/public_html/app/Http/Middleware/FreezeSEO.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#47 [internal function]: App\Http\Middleware\FreezeSEO->handle(Object(Xpressengine\Http\Request), Object(Closure))
#48 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#49 /xxx/public_html/app/Http/Middleware/Purifying.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#50 [internal function]: App\Http\Middleware\Purifying->handle(Object(Xpressengine\Http\Request), Object(Closure))
#51 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#52 /xxx/public_html/app/Http/Middleware/LangPreprocessor.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#53 [internal function]: App\Http\Middleware\LangPreprocessor->handle(Object(Xpressengine\Http\Request), Object(Closure))
#54 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#55 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#56 /xxx/public_html/app/Http/Middleware/ExceptAppendableVerifyCsrfToken.php(21): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Xpressengine\Http\Request), Object(Closure))
#57 [internal function]: App\Http\Middleware\ExceptAppendableVerifyCsrfToken->handle(Object(Xpressengine\Http\Request), Object(Closure))
#58 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#59 /xxx/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#60 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Xpressengine\Http\Request), Object(Closure))
#61 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#62 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#63 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Xpressengine\Http\Request), Object(Closure))
#64 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#65 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#66 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Xpressengine\Http\Request), Object(Closure))
#67 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#68 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#69 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Xpressengine\Http\Request), Object(Closure))
#70 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#71 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#72 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Xpressengine\Http\Request), Object(Closure))
#73 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#74 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#75 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#76 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#77 /xxx/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Xpressengine\Http\Request))
#78 /xxx/public_html/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Xpressengine\Http\Request))
#79 {main}
```

**Comment by hhgyu** [comment]
개발 환경은
WebServer : Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.0.3
PHP Version : 7.0.3
Debug Mode :
Cache Driver : file
Maintenance : Off
TimeZone : Asia/Seoul
입니다.

**Comment by hhgyu** [comment]
#100 여기서 수정된네요.

**Comment by akasima** [comment]
뭔가 좀 많이 꼬인것 같네요. 브랜치 옮겨다니며 작업하다가 커밋이 잘못된게 아닌가 싶은데요; 확인하려면 시간이 좀 걸릴것 같습니다.

**Comment by khongchi** [comment]
#94에서 다룬 이슈입니다.
