### ISSUE TITLE
관리자 대시보드에서 플러그인 목록이 조회되지 않음

### ISSUE THREAD

**Issue by mAKEkr** [xpressengine/xpressengine#24]
(마크다운을 제대로 안올려서 타 이슈까지 레퍼런스되었습니다 죄송합니다.) (__)

```
[2015-11-16 04:24:21] local.ERROR: ErrorException: file_put_contents(/srv/XE3/storage/framework/plugins/10/ae/10ae9fc7d453b0dd525d0edf2ede7961): failed to open stream: Permission denied in /srv/XE3/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:81
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/srv/XE3/vendor...', 81, Array)
#1 /srv/XE3/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(81): file_put_contents('/srv/XE3/storag...', '9999999999s:151...', 0)
#2 /srv/XE3/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(102): Illuminate\Filesystem\Filesystem->put('/srv/XE3/storag...', '9999999999s:151...')
#3 /srv/XE3/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(157): Illuminate\Cache\FileStore->put('list', '9999999999s:151...', 0)
#4 /srv/XE3/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(183): Illuminate\Cache\FileStore->forever('list', '{"alice":{"id":...')
#5 /srv/XE3/core/src/Xpressengine/Plugin/Cache/FilePluginCache.php(84): Illuminate\Cache\Repository->forever('list', '{"alice":{"id":...')
#6 /srv/XE3/core/src/Xpressengine/Plugin/PluginCollection.php(124): Xpressengine\Plugin\Cache\FilePluginCache->setPluginsToCache(Array)
#7 /srv/XE3/core/src/Xpressengine/Plugin/PluginCollection.php(103): Xpressengine\Plugin\PluginCollection->refresh()
#8 /srv/XE3/core/src/Xpressengine/Plugin/PluginHandler.php(378): Xpressengine\Plugin\PluginCollection->initialize(true)
#9 [internal function]: Xpressengine\Plugin\PluginHandler->getAllPlugins(true)
#10 /srv/XE3/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(106): call_user_func_array('parent::getAllP...', Array)
#11 [internal function]: Proxy_Xpressengine_Plugin_PluginHandler->_proxyTargetCall('getAllPlugins', Array)
#12 /srv/XE3/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(90): call_user_func_array(Array, Array)
#13 [internal function]: Proxy_Xpressengine_Plugin_PluginHandler->Xpressengine\Interception\Proxy\{closure}(true)
#14 /srv/XE3/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(94): call_user_func_array(Object(Closure), Array)
#15 [internal function]: Xpressengine\Interception\ProxyInvocationHandler->__invoke(true)
#16 /srv/XE3/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(72): call_user_func_array(Object(Xpressengine\Interception\ProxyInvocationHandler), Array)
#17 /srv/XE3/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(92): Xpressengine\Interception\ProxyInvocationHandler->callProxy(Array, Object(Closure))
#18 /srv/XE3/storage/interception/Proxy_Xpressengine_Plugin_PluginHandler.php(60): Proxy_Xpressengine_Plugin_PluginHandler->_proxyMethodCall('getAllPlugins', Array)
#19 /srv/XE3/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(216): Proxy_Xpressengine_Plugin_PluginHandler->getAllPlugins(true)
#20 /srv/XE3/app/Http/Controllers/PluginController.php(35): Illuminate\Support\Facades\Facade::__callStatic('getAllPlugins', Array)
#21 [internal function]: App\Http\Controllers\PluginController->index(Object(Xpressengine\Http\Request))
#22 /srv/XE3/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#23 /srv/XE3/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#24 /srv/XE3/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\PluginController), Object(Illuminate\Routing\Route), 'index')
#25 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Xpressengine\Http\Request))
#26 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#28 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#29 /srv/XE3/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /srv/XE3/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\PluginController), Object(Illuminate\Routing\Route), Object(Xpressengine\Http\Request), 'index')
#31 /srv/XE3/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Xpressengine\Http\Request), 'App\\Http\\Contro...', 'index')
#32 /srv/XE3/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Xpressengine\Http\Request))
#33 /srv/XE3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(712): Illuminate\Routing\Route->run(Object(Xpressengine\Http\Request))
#34 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Xpressengine\Http\Request))
#35 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#36 /srv/XE3/core/src/Xpressengine/Settings/SettingsMiddleware.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#37 [internal function]: Xpressengine\Settings\SettingsMiddleware->handle(Object(Xpressengine\Http\Request), Object(Closure))
#38 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#40 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#41 /srv/XE3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(714): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /srv/XE3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(677): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Xpressengine\Http\Request))
#43 /srv/XE3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(639): Illuminate\Routing\Router->dispatchToRoute(Object(Xpressengine\Http\Request))
#44 /srv/XE3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Xpressengine\Http\Request))
#45 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Xpressengine\Http\Request))
#46 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#47 /srv/XE3/app/Http/Middleware/FreezeSEO.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#48 [internal function]: App\Http\Middleware\FreezeSEO->handle(Object(Xpressengine\Http\Request), Object(Closure))
#49 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#50 /srv/XE3/app/Http/Middleware/Purifying.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#51 [internal function]: App\Http\Middleware\Purifying->handle(Object(Xpressengine\Http\Request), Object(Closure))
#52 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#53 /srv/XE3/app/Http/Middleware/SiteIdentify.php(72): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#54 [internal function]: App\Http\Middleware\SiteIdentify->handle(Object(Xpressengine\Http\Request), Object(Closure))
#55 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#56 /srv/XE3/app/Http/Middleware/LangPreprocessor.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#57 [internal function]: App\Http\Middleware\LangPreprocessor->handle(Object(Xpressengine\Http\Request), Object(Closure))
#58 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#59 /srv/XE3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#60 /srv/XE3/app/Http/Middleware/ExceptAppendableVerifyCsrfToken.php(21): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Xpressengine\Http\Request), Object(Closure))
#61 [internal function]: App\Http\Middleware\ExceptAppendableVerifyCsrfToken->handle(Object(Xpressengine\Http\Request), Object(Closure))
#62 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#63 /srv/XE3/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#64 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Xpressengine\Http\Request), Object(Closure))
#65 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#66 /srv/XE3/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#67 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Xpressengine\Http\Request), Object(Closure))
#68 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#69 /srv/XE3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#70 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Xpressengine\Http\Request), Object(Closure))
#71 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#72 /srv/XE3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#73 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Xpressengine\Http\Request), Object(Closure))
#74 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#75 /srv/XE3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#76 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Xpressengine\Http\Request), Object(Closure))
#77 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#78 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#79 /srv/XE3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#80 /srv/XE3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#81 /srv/XE3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Xpressengine\Http\Request))
#82 /srv/XE3/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Xpressengine\Http\Request))
#83 {main}  
[2015-11-16 04:24:21] local.ERROR: Skin을 찾을 수 없습니다  
[2015-11-16 04:24:21] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Skin을 찾을 수 없습니다
  thrown in /srv/XE3/core/src/Xpressengine/Skin/SkinHandler.php:399
Stack trace:
#0 /srv/XE3/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /srv/XE3/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /srv/XE3/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 {main}  
```

코어에서 건드린건 없습니다.

PHP 7.0.0-RC7 / Nginx 1.9.6 / MariaDB 10.1 환경입니다.

**Comment by khongchi** [comment]
storage 디렉토리의 퍼미션 문제로 보입니다. 새로 설치하시고 퍼미션 설정하시면 해결될 것입니다.
