### ISSUE TITLE
파일첨부 시 "시스템에 오류가 있습니다. 관리자에게 문의하세요."

### ISSUE THREAD

**Issue by neoche** [xpressengine/xpressengine#342]
```
[https://xpressengine.io/qna/%ED%8C%8C%EC%9D%BC%EC%B2%A8%EB%B6%80-%EC%8B%9C-%EC%8B%9C%EC%8A%A4%ED%85%9C%EC%97%90-%EC%98%A4%EB%A5%98%EA%B0%80-%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4-%EA%B4%80%EB%A6%AC%EC%9E%90%EC%97%90%EA%B2%8C-%EB%AC%B8%EC%9D%98%ED%95%98%EC%84%B8%EC%9A%94-1#](https://xpressengine.io/qna/%ED%8C%8C%EC%9D%BC%EC%B2%A8%EB%B6%80-%EC%8B%9C-%EC%8B%9C%EC%8A%A4%ED%85%9C%EC%97%90-%EC%98%A4%EB%A5%98%EA%B0%80-%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4-%EA%B4%80%EB%A6%AC%EC%9E%90%EC%97%90%EA%B2%8C-%EB%AC%B8%EC%9D%98%ED%95%98%EC%84%B8%EC%9A%94-1#)


[2016-11-09 21:57:01] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Illuminate\Database\Grammar::parameterize() must be of the type array, float given, called in /home/hosting_users/checkmybaggage/www/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 672 in /home/hosting_users/checkmybaggage/www/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:118
Stack trace:
#0 /home/hosting_users/checkmybaggage/www/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(672): Illuminate\Database\Grammar->parameterize(1.3364375)
#1 /home/hosting_users/checkmybaggage/www/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(690): Illuminate\Database\Query\Grammars\Grammar->compileInsert(Object(Xpressengine\Database\DynamicQuery), Array)
#2 /home/hosting_users/checkmybaggage/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1839): Illuminate\Database\Query\Grammars\Grammar->compileInsertGetId(Object(Xpressengine\Database\DynamicQuery), Array, 'id')
#3 /home/hosting_users/checkmybaggage/www/core/src/Xpressengine/Database/DynamicQuery.php(265): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#4 [internal function]: Xpressengine\Database\DynamicQuery->insertGetId(Array, 'id')
#5 /home/hosting_users/checkmybaggage/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1015): call_user_func_array(Array, Array)
#6 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(10517): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#7 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(10506): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Xpressengine\Database\Eloquent\Builder), Array)
#8 /home/hosting_users/checkmybaggage/www/core/src/Xpressengine/Database/Eloquent/DynamicModel.php(288): Illuminate\Database\Eloquent\Model->performInsert(Object(Xpressengine\Database\Eloquent\Builder), Array)
#9 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(10457): Xpressengine\Database\Eloquent\DynamicModel->performInsert(Object(Xpressengine\Database\Eloquent\Builder), Array)
#10 /home/hosting_users/checkmybaggage/www/core/src/Xpressengine/Database/Eloquent/DynamicModel.php(303): Illuminate\Database\Eloquent\Model->save(Array)
#11 /home/hosting_users/checkmybaggage/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(317): Xpressengine\Database\Eloquent\DynamicModel->save()
#12 /home/hosting_users/checkmybaggage/www/core/src/Xpressengine/Media/Handlers/VideoHandler.php(147): Illuminate\Database\Eloquent\Relations\HasOneOrMany->create(Array)
#13 /home/hosting_users/checkmybaggage/www/core/src/Xpressengine/Media/MediaManager.php(186): Xpressengine\Media\Handlers\VideoHandler->make(Object(Xpressengine\Storage\File))
#14 [internal function]: Xpressengine\Media\MediaManager->make(Object(Xpressengine\Storage\File))
#15 /home/hosting_users/checkmybaggage/www/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(104): call_user_func_array('parent::make', Array)
#16 [internal function]: Proxy_Xpressengine_Media_MediaManager->_proxyTargetCall('make', Array)
#17 /home/hosting_users/checkmybaggage/www/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(88): call_user_func_array(Array, Array)
#18 [internal function]: Proxy_Xpressengine_Media_MediaManager->Xpressengine\Interception\Proxy\{closure}(Object(Xpressengine\Storage\File))
#19 /home/hosting_users/checkmybaggage/www/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(96): call_user_func_array(Object(Closure), Array)
#20 [internal function]: Xpressengine\Interception\ProxyInvocationHandler->__invoke(Object(Xpressengine\Storage\File))
#21 /home/hosting_users/checkmybaggage/www/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(74): call_user_func_array(Object(Xpressengine\Interception\ProxyInvocationHandler), Array)
#22 /home/hosting_users/checkmybaggage/www/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(90): Xpressengine\Interception\ProxyInvocationHandler->callProxy(Array, Object(Closure))
#23 /home/hosting_users/checkmybaggage/www/storage/app/interception/Proxy_Xpressengine_Media_MediaManager.php(35): Proxy_Xpressengine_Media_MediaManager->_proxyMethodCall('make', Array)
#24 /home/hosting_users/checkmybaggage/www/app/Http/Controllers/EditorController.php(161): Proxy_Xpressengine_Media_MediaManager->make(Object(Xpressengine\Storage\File))
#25 [internal function]: App\Http\Controllers\EditorController->fileUpload(Object(Xpressengine\Http\Request), Object(Proxy_Xpressengine_Editor_EditorHandler), Object(Proxy_Xpressengine_Storage_Storage), Object(Proxy_Xpressengine_Media_MediaManager), '5f6552b3')
#26 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(8923): call_user_func_array(Array, Array)
#27 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(8992): Illuminate\Routing\Controller->callAction('fileUpload', Array)
#28 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(8972): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\EditorController), Object(Illuminate\Routing\Route), 'fileUpload')
#29 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Xpressengine\Http\Request))
#30 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9643): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#32 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9625): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#33 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(8973): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(8958): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\EditorController), Object(Illuminate\Routing\Route), Object(Xpressengine\Http\Request), 'fileUpload')
#35 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(7907): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Xpressengine\Http\Request), 'App\\Http\\Contro...', 'fileUpload')
#36 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(7878): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Xpressengine\Http\Request))
#37 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(7531): Illuminate\Routing\Route->run(Object(Xpressengine\Http\Request))
#38 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Xpressengine\Http\Request))
#39 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9643): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#41 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9625): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#42 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(7532): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(7520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Xpressengine\Http\Request))
#44 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(7505): Illuminate\Routing\Router->dispatchToRoute(Object(Xpressengine\Http\Request))
#45 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Xpressengine\Http\Request))
#46 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Xpressengine\Http\Request))
#47 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9643): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#48 /home/hosting_users/checkmybaggage/www/app/Http/Middleware/FreezeSEO.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#49 [internal function]: App\Http\Middleware\FreezeSEO->handle(Object(Xpressengine\Http\Request), Object(Closure))
#50 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9635): call_user_func_array(Array, Array)
#51 /home/hosting_users/checkmybaggage/www/app/Http/Middleware/Purifying.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#52 [internal function]: App\Http\Middleware\Purifying->handle(Object(Xpressengine\Http\Request), Object(Closure))
#53 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9635): call_user_func_array(Array, Array)
#54 /home/hosting_users/checkmybaggage/www/app/Http/Middleware/LangPreprocessor.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#55 [internal function]: App\Http\Middleware\LangPreprocessor->handle(Object(Xpressengine\Http\Request), Object(Closure))
#56 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9635): call_user_func_array(Array, Array)
#57 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#58 /home/hosting_users/checkmybaggage/www/app/Http/Middleware/ExceptAppendableVerifyCsrfToken.php(21): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Xpressengine\Http\Request), Object(Closure))
#59 [internal function]: App\Http\Middleware\ExceptAppendableVerifyCsrfToken->handle(Object(Xpressengine\Http\Request), Object(Closure))
#60 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9635): call_user_func_array(Array, Array)
#61 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(12994): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#62 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Xpressengine\Http\Request), Object(Closure))
#63 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9635): call_user_func_array(Array, Array)
#64 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(11586): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#65 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Xpressengine\Http\Request), Object(Closure))
#66 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9635): call_user_func_array(Array, Array)
#67 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(12731): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#68 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Xpressengine\Http\Request), Object(Closure))
#69 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9635): call_user_func_array(Array, Array)
#70 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(12668): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#71 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Xpressengine\Http\Request), Object(Closure))
#72 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9635): call_user_func_array(Array, Array)
#73 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#74 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Xpressengine\Http\Request), Object(Closure))
#75 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9635): call_user_func_array(Array, Array)
#76 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#77 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(9625): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#78 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#79 /home/hosting_users/checkmybaggage/www/bootstrap/cache/compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Xpressengine\Http\Request))
#80 /home/hosting_users/checkmybaggage/www/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Xpressengine\Http\Request))
#81 {main}  
```

**Comment by jhyeon1010** [comment]
@seungmanchoi  섬네일이 제공되지 않는 미디어 파일업로드의 경우 에디터 js 에서 섬네일의 url 을 획득하는 시도가 있어 오류가 발생합니다.

**Comment by seungmanchoi** [comment]
[https://github.com/xpressengine/plugin-ckeditor/issues/14](ckeditor #14 )

**Comment by seungmanchoi** [comment]
파일첨부시 썸네일이 생성되지 않는 업로드 파일 중 response url에서 썸네일 경로를 획득하려는 시도가 있어 분기될 수 있도록 수정
