### ISSUE TITLE
회원 단계 구분에 따른 사이트 오류

### ISSUE THREAD

**Issue by lamir0star** [xpressengine/xpressengine#516]
여러가지 작업을 해서 원인은 파악이 안되는데요.
예상되는 연관 작업은, 회원 입력 항목 추가 ( 추가 안됨 ), 회원 구분을 ( 준회원, 정회원 2단계에서 4개 단계로 변경 )

core\src\Xpressengine\User\Rating.php 파일의 line 74
throw new UnknownCriterionException(compact('criterion'));

오류로 유저페이지 500에러 표시 후 접속 이 안되는 문제가 있었습니다. ( 관리화면은 표시됨 )

로그 첨부합니다.
```
[2017-07-28 17:43:21] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Xpressengine\User\Exceptions\UnknownCriterionException: Unknown criterion [] in /home/hosting_users/makerhub/www/core/src/Xpressengine/User/Rating.php:75
Stack trace:
#0 /home/hosting_users/makerhub/www/core/src/Xpressengine/Permission/Policy.php(217): Xpressengine\User\Rating::compare('super', NULL)
#1 /home/hosting_users/makerhub/www/core/src/Xpressengine/Permission/Policy.php(147): Xpressengine\Permission\Policy->ratingInspect(Object(Xpressengine\User\Models\User), NULL)
#2 /home/hosting_users/makerhub/www/core/src/Xpressengine/Permission/Policy.php(93): Xpressengine\Permission\Policy->checker(Object(Xpressengine\User\Models\User), 'rating', NULL)
#3 /home/hosting_users/makerhub/www/core/src/Xpressengine/Menu/MenuItemPolicy.php(61): Xpressengine\Permission\Policy->check(Object(Xpressengine\User\Models\User), Object(Xpressengine\Permission\Permission), 'visible')
#4 [internal function]: Xpressengine\Menu\MenuItemPolicy->visible(Object(Xpressengine\User\Models\User), Object(Xpressengine\Menu\Models\ in /home/hosting_users/makerhub/www/core/src/Xpressengine/User/Rating.php:75
Stack trace:
#0 {main}  
```

**Comment by khongchi** [comment]
살펴보니 회원관련 작업에서의 문제 같지는 않고, 접속한 메뉴에 지정된 권한에 문제가 있는 것 같은데요.

메뉴(사이트맵) 관련 작업은 하지 않으셨나요?
최근 사이트맵 관련 오류가 있어서 접속한 메뉴의 권한설정이 제대로 안 됐을 수 있습니다.

가능하다면 해당 메뉴의 권한 설정을 다시 한번 해주시고 시도해보시기 바랍니다.

감사합니다.
