### ISSUE TITLE
제거된 컴포넌트를 탐색하는 오류

### ISSUE THREAD

**Issue by jhyeon1010** [xpressengine/xpressengine#520]
플러그인이 업데이트 되면서, 기존 버전에서 존재하던 컴포넌트가 삭제되어진 경우가 있습니다.
이럴때 plugin 패키지에서 캐싱된 데이터를 이용하여 boot 과정을 처리하다보니 오류를 발생 시킵니다.

```
[2017-07-27 12:24:38] production.INFO: [plugin operation] start running composer run [pid=22687]  
[2017-07-27 12:28:04] production.INFO: [plugin operation] plugin operation finished. [exit code: 127, memory usage: 812134384]  
[2017-07-27 13:40:04] production.ERROR: Xpressengine\Plugin\Exceptions\ComponentNotFoundException: "Xpressengine\Plugins\Board\Widgets\GalleryWidget" class not found in "board" plugin in /home/hosting_users/makerhub/www/core/src/Xpressengine/Plugin/PluginRegister.php:197
Stack trace:
#0 /home/hosting_users/makerhub/www/core/src/Xpressengine/Plugin/PluginRegister.php(76): Xpressengine\Plugin\PluginRegister->setComponentInfo(Array)
#1 [internal function]: Xpressengine\Plugin\PluginRegister->addByEntity(Object(Xpressengine\Plugin\PluginEntity))
#2 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(104): call_user_func_array('parent::addByEn...', Array)
#3 [internal function]: Proxy_Xpressengine_Plugin_PluginRegister->_proxyTargetCall('addByEntity', Array)
#4 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(88): call_user_func_array(Array, Array)
#5 [internal function]: Proxy_Xpressengine_Plugin_PluginRegister->Xpressengine\Interception\Proxy\{closure}(Object(Xpressengine\Plugin\PluginEntity))
#6 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(96): call_user_func_array(Object(Closure), Array)
#7 [internal function]: Xpressengine\Interception\ProxyInvocationHandler->__invoke(Object(Xpressengine\Plugin\PluginEntity))
#8 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(74): call_user_func_array(Object(Xpressengine\Interception\ProxyInvocationHandler), Array)
#9 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(90): Xpressengine\Interception\ProxyInvocationHandler->callProxy(Array, Object(Closure))
#10 /home/hosting_users/makerhub/www/storage/app/interception/Proxy_Xpressengine_Plugin_PluginRegister.php(15): Proxy_Xpressengine_Plugin_PluginRegister->_proxyMethodCall('addByEntity', Array)
#11 /home/hosting_users/makerhub/www/core/src/Xpressengine/Plugin/PluginHandler.php(383): Proxy_Xpressengine_Plugin_PluginRegister->addByEntity(Object(Xpressengine\Plugin\PluginEntity))
#12 [internal function]: Xpressengine\Plugin\PluginHandler->registerPlugin(Object(Xpressengine\Plugin\PluginEntity))
#13 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(104): call_user_func_array('parent::registe...', Array)
#14 [internal function]: Proxy_Xpressengine_Plugin_PluginHandler->_proxyTargetCall('registerPlugin', Array)
#15 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(88): call_user_func_array(Array, Array)
#16 [internal function]: Proxy_Xpressengine_Plugin_PluginHandler->Xpressengine\Interception\Proxy\{closure}(Object(Xpressengine\Plugin\PluginEntity))
#17 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(96): call_user_func_array(Object(Closure), Array)
#18 [internal function]: Xpressengine\Interception\ProxyInvocationHandler->__invoke(Object(Xpressengine\Plugin\PluginEntity))
#19 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(74): call_user_func_array(Object(Xpressengine\Interception\ProxyInvocationHandler), Array)
#20 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(90): Xpressengine\Interception\ProxyInvocationHandler->callProxy(Array, Object(Closure))
#21 /home/hosting_users/makerhub/www/storage/app/interception/Proxy_Xpressengine_Plugin_PluginHandler.php(55): Proxy_Xpressengine_Plugin_PluginHandler->_proxyMethodCall('registerPlugin', Array)
#22 /home/hosting_users/makerhub/www/core/src/Xpressengine/Plugin/PluginHandler.php(361): Proxy_Xpressengine_Plugin_PluginHandler->registerPlugin(Object(Xpressengine\Plugin\PluginEntity))
#23 [internal function]: Xpressengine\Plugin\PluginHandler->bootPlugins()
#24 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(104): call_user_func_array('parent::bootPlu...', Array)
#25 [internal function]: Proxy_Xpressengine_Plugin_PluginHandler->_proxyTargetCall('bootPlugins', Array)
#26 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(88): call_user_func_array(Array, Array)
#27 [internal function]: Proxy_Xpressengine_Plugin_PluginHandler->Xpressengine\Interception\Proxy\{closure}()
#28 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(96): call_user_func_array(Object(Closure), Array)
#29 [internal function]: Xpressengine\Interception\ProxyInvocationHandler->__invoke()
#30 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(74): call_user_func_array(Object(Xpressengine\Interception\ProxyInvocationHandler), Array)
#31 /home/hosting_users/makerhub/www/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(90): Xpressengine\Interception\ProxyInvocationHandler->callProxy(Array, Object(Closure))
#32 /home/hosting_users/makerhub/www/storage/app/interception/Proxy_Xpressengine_Plugin_PluginHandler.php(50): Proxy_Xpressengine_Plugin_PluginHandler->_proxyMethodCall('bootPlugins', Array)
#33 /home/hosting_users/makerhub/www/app/Providers/PluginServiceProvider.php(161): Proxy_Xpressengine_Plugin_PluginHandler->bootPlugins()
#34 [internal function]: App\Providers\PluginServiceProvider->App\Providers\{closure}(Object(Illuminate\Foundation\Application))
#35 /home/hosting_users/makerhub/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(773): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#36 /home/hosting_users/makerhub/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(722): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#37 /home/hosting_users/makerhub/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#38 /home/hosting_users/makerhub/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#39 /home/hosting_users/makerhub/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(222): Illuminate\Foundation\Application->bootstrapWith(Array)
#40 /home/hosting_users/makerhub/www/app/Http/Kernel.php(65): Illuminate\Foundation\Http\Kernel->bootstrap()
#41 /home/hosting_users/makerhub/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): App\Http\Kernel->bootstrap()
#42 /home/hosting_users/makerhub/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Xpressengine\Http\Request))
#43 /home/hosting_users/makerhub/www/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Xpressengine\Http\Request))
#44 {main}  

```

위 에러 메시지는 board 0.9.17 버전에 존재하던 `Xpressengine\Plugins\Board\Widgets\GalleryWidget` 이 다음 버전에 사라짐으로 인해 발생하는 오류 메시지 입니다.

**Comment by jhyeon1010** [comment]
플러그인이 업데이트 될때 캐시가 갱신되도록 수정 바랍니다.
