### ISSUE TITLE
설치시 http 500에러가 발생합니다

### ISSUE THREAD

**Issue by centell** [xpressengine/xpressengine#685]
공식 홈페이지의 [이 분](https://www.xpressengine.io/qna/xe-%EC%84%A4%EC%B9%98-%EC%8B%9C-500-%EC%97%90%EB%9F%AC-%EB%B0%9C%EC%83%9D?title_pure_content=500)과 비슷한 케이스입니다.

`bootstrap/cashe`, `config/production`, `plugins`, `storage`, `vendor`, `composer.lock` 등의 권한을 707로 맞춘 상태였고, 사용하는 건 가비아 호스팅 PHP 7.0 환경입니다.

루트 디렉터리에 XE3의 파일들을 FTP를 이용해 업로드한 뒤 웹 설치로 접근했습니다.
특이한건, 루트 디렉터리에 test.php 같은 파일을 만들어서 들어가려 해도 500에러가 발생합니다. 

로그 내용은 아래에 덧붙입니다.

```
[2018-02-07 07:09:47] production.ERROR: ReflectionException: Class xe.presenter does not exist in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 /www_root/bootstrap/cache/compiled.php(1291): ReflectionClass->__construct('xe.presenter')
#1 /www_root/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('xe.presenter', Array)
#2 /www_root/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('xe.presenter', Array)
#3 /www_root/bootstrap/cache/compiled.php(1478): Illuminate\Foundation\Application->make('xe.presenter')
#4 /www_root/bootstrap/cache/compiled.php(6063): Illuminate\Container\Container->offsetGet('xe.presenter')
#5 /www_root/bootstrap/cache/compiled.php(6049): Illuminate\Support\Facades\Facade::resolveFacadeInstance('xe.presenter')
#6 /www_root/bootstrap/cache/compiled.php(6083): Illuminate\Support\Facades\Facade::getFacadeRoot()
#7 /www_root/app/Exceptions/Handler.php(151): Illuminate\Support\Facades\Facade::__callStatic('setSkinTargetId', Array)
#8 /www_root/bootstrap/cache/compiled.php(2327): App\Exceptions\Handler->render(Object(Xpressengine\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#9 /www_root/bootstrap/cache/compiled.php(2243): Illuminate\Foundation\Http\Kernel->renderException(Object(Xpressengine\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#10 /www_root/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Xpressengine\Http\Request))
#11 {main}  
[2018-02-07 07:09:47] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ReflectionException: Class xe.presenter does not exist in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 /www_root/bootstrap/cache/compiled.php(1291): ReflectionClass->__construct('xe.presenter')
#1 /www_root/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('xe.presenter', Array)
#2 /www_root/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('xe.presenter', Array)
#3 /www_root/bootstrap/cache/compiled.php(1478): Illuminate\Foundation\Application->make('xe.presenter')
#4 /www_root/bootstrap/cache/compiled.php(6063): Illuminate\Container\Container->offsetGet('xe.presenter')
#5 /www_root/bootstrap/cache/compiled.php(6049): Illuminate\Support\Facades\Facade::resolveFacadeInstance('xe.presenter')
#6 /www_root/bootstrap/cache/compiled.php(6083): Illuminate\Support\Facades\Facade::getFacadeRoot()
#7 /www_root/app/Exceptions/Handler.php(151): Illuminate\Support\Facades\Facade::__callStatic('setSkinTargetId', Array)
#8 /www_root/bootstrap/cache/comp in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 {main}  
[2018-02-07 07:09:47] production.ERROR: ReflectionException: Class xe.presenter does not exist in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 /www_root/bootstrap/cache/compiled.php(1291): ReflectionClass->__construct('xe.presenter')
#1 /www_root/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('xe.presenter', Array)
#2 /www_root/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('xe.presenter', Array)
#3 /www_root/bootstrap/cache/compiled.php(1478): Illuminate\Foundation\Application->make('xe.presenter')
#4 /www_root/bootstrap/cache/compiled.php(6063): Illuminate\Container\Container->offsetGet('xe.presenter')
#5 /www_root/bootstrap/cache/compiled.php(6049): Illuminate\Support\Facades\Facade::resolveFacadeInstance('xe.presenter')
#6 /www_root/bootstrap/cache/compiled.php(6083): Illuminate\Support\Facades\Facade::getFacadeRoot()
#7 /www_root/app/Exceptions/Handler.php(151): Illuminate\Support\Facades\Facade::__callStatic('setSkinTargetId', Array)
#8 /www_root/bootstrap/cache/compiled.php(2327): App\Exceptions\Handler->render(Object(Xpressengine\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#9 /www_root/bootstrap/cache/compiled.php(2243): Illuminate\Foundation\Http\Kernel->renderException(Object(Xpressengine\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#10 /www_root/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Xpressengine\Http\Request))
#11 {main}  
[2018-02-07 07:09:47] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ReflectionException: Class xe.presenter does not exist in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 /www_root/bootstrap/cache/compiled.php(1291): ReflectionClass->__construct('xe.presenter')
#1 /www_root/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('xe.presenter', Array)
#2 /www_root/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('xe.presenter', Array)
#3 /www_root/bootstrap/cache/compiled.php(1478): Illuminate\Foundation\Application->make('xe.presenter')
#4 /www_root/bootstrap/cache/compiled.php(6063): Illuminate\Container\Container->offsetGet('xe.presenter')
#5 /www_root/bootstrap/cache/compiled.php(6049): Illuminate\Support\Facades\Facade::resolveFacadeInstance('xe.presenter')
#6 /www_root/bootstrap/cache/compiled.php(6083): Illuminate\Support\Facades\Facade::getFacadeRoot()
#7 /www_root/app/Exceptions/Handler.php(151): Illuminate\Support\Facades\Facade::__callStatic('setSkinTargetId', Array)
#8 /www_root/bootstrap/cache/comp in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 {main}  
[2018-02-07 07:36:21] production.ERROR: ReflectionException: Class xe.presenter does not exist in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 /www_root/bootstrap/cache/compiled.php(1291): ReflectionClass->__construct('xe.presenter')
#1 /www_root/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('xe.presenter', Array)
#2 /www_root/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('xe.presenter', Array)
#3 /www_root/bootstrap/cache/compiled.php(1478): Illuminate\Foundation\Application->make('xe.presenter')
#4 /www_root/bootstrap/cache/compiled.php(6063): Illuminate\Container\Container->offsetGet('xe.presenter')
#5 /www_root/bootstrap/cache/compiled.php(6049): Illuminate\Support\Facades\Facade::resolveFacadeInstance('xe.presenter')
#6 /www_root/bootstrap/cache/compiled.php(6083): Illuminate\Support\Facades\Facade::getFacadeRoot()
#7 /www_root/app/Exceptions/Handler.php(151): Illuminate\Support\Facades\Facade::__callStatic('setSkinTargetId', Array)
#8 /www_root/bootstrap/cache/compiled.php(2327): App\Exceptions\Handler->render(Object(Xpressengine\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#9 /www_root/bootstrap/cache/compiled.php(2243): Illuminate\Foundation\Http\Kernel->renderException(Object(Xpressengine\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#10 /www_root/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Xpressengine\Http\Request))
#11 {main}  
[2018-02-07 07:36:21] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ReflectionException: Class xe.presenter does not exist in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 /www_root/bootstrap/cache/compiled.php(1291): ReflectionClass->__construct('xe.presenter')
#1 /www_root/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('xe.presenter', Array)
#2 /www_root/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('xe.presenter', Array)
#3 /www_root/bootstrap/cache/compiled.php(1478): Illuminate\Foundation\Application->make('xe.presenter')
#4 /www_root/bootstrap/cache/compiled.php(6063): Illuminate\Container\Container->offsetGet('xe.presenter')
#5 /www_root/bootstrap/cache/compiled.php(6049): Illuminate\Support\Facades\Facade::resolveFacadeInstance('xe.presenter')
#6 /www_root/bootstrap/cache/compiled.php(6083): Illuminate\Support\Facades\Facade::getFacadeRoot()
#7 /www_root/app/Exceptions/Handler.php(151): Illuminate\Support\Facades\Facade::__callStatic('setSkinTargetId', Array)
#8 /www_root/bootstrap/cache/comp in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 {main}  
[2018-02-07 09:56:08] production.ERROR: ReflectionException: Class xe.presenter does not exist in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 /www_root/bootstrap/cache/compiled.php(1291): ReflectionClass->__construct('xe.presenter')
#1 /www_root/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('xe.presenter', Array)
#2 /www_root/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('xe.presenter', Array)
#3 /www_root/bootstrap/cache/compiled.php(1478): Illuminate\Foundation\Application->make('xe.presenter')
#4 /www_root/bootstrap/cache/compiled.php(6063): Illuminate\Container\Container->offsetGet('xe.presenter')
#5 /www_root/bootstrap/cache/compiled.php(6049): Illuminate\Support\Facades\Facade::resolveFacadeInstance('xe.presenter')
#6 /www_root/bootstrap/cache/compiled.php(6083): Illuminate\Support\Facades\Facade::getFacadeRoot()
#7 /www_root/app/Exceptions/Handler.php(151): Illuminate\Support\Facades\Facade::__callStatic('setSkinTargetId', Array)
#8 /www_root/bootstrap/cache/compiled.php(2327): App\Exceptions\Handler->render(Object(Xpressengine\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#9 /www_root/bootstrap/cache/compiled.php(2243): Illuminate\Foundation\Http\Kernel->renderException(Object(Xpressengine\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#10 /www_root/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Xpressengine\Http\Request))
#11 {main}  
[2018-02-07 09:56:08] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ReflectionException: Class xe.presenter does not exist in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 /www_root/bootstrap/cache/compiled.php(1291): ReflectionClass->__construct('xe.presenter')
#1 /www_root/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('xe.presenter', Array)
#2 /www_root/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('xe.presenter', Array)
#3 /www_root/bootstrap/cache/compiled.php(1478): Illuminate\Foundation\Application->make('xe.presenter')
#4 /www_root/bootstrap/cache/compiled.php(6063): Illuminate\Container\Container->offsetGet('xe.presenter')
#5 /www_root/bootstrap/cache/compiled.php(6049): Illuminate\Support\Facades\Facade::resolveFacadeInstance('xe.presenter')
#6 /www_root/bootstrap/cache/compiled.php(6083): Illuminate\Support\Facades\Facade::getFacadeRoot()
#7 /www_root/app/Exceptions/Handler.php(151): Illuminate\Support\Facades\Facade::__callStatic('setSkinTargetId', Array)
#8 /www_root/bootstrap/cache/comp in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 {main}  
[2018-02-07 10:08:02] production.ERROR: ReflectionException: Class xe.presenter does not exist in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 /www_root/bootstrap/cache/compiled.php(1291): ReflectionClass->__construct('xe.presenter')
#1 /www_root/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('xe.presenter', Array)
#2 /www_root/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('xe.presenter', Array)
#3 /www_root/bootstrap/cache/compiled.php(1478): Illuminate\Foundation\Application->make('xe.presenter')
#4 /www_root/bootstrap/cache/compiled.php(6063): Illuminate\Container\Container->offsetGet('xe.presenter')
#5 /www_root/bootstrap/cache/compiled.php(6049): Illuminate\Support\Facades\Facade::resolveFacadeInstance('xe.presenter')
#6 /www_root/bootstrap/cache/compiled.php(6083): Illuminate\Support\Facades\Facade::getFacadeRoot()
#7 /www_root/app/Exceptions/Handler.php(151): Illuminate\Support\Facades\Facade::__callStatic('setSkinTargetId', Array)
#8 /www_root/bootstrap/cache/compiled.php(2327): App\Exceptions\Handler->render(Object(Xpressengine\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#9 /www_root/bootstrap/cache/compiled.php(2243): Illuminate\Foundation\Http\Kernel->renderException(Object(Xpressengine\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#10 /www_root/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Xpressengine\Http\Request))
#11 {main}  
[2018-02-07 10:08:02] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ReflectionException: Class xe.presenter does not exist in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 /www_root/bootstrap/cache/compiled.php(1291): ReflectionClass->__construct('xe.presenter')
#1 /www_root/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('xe.presenter', Array)
#2 /www_root/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('xe.presenter', Array)
#3 /www_root/bootstrap/cache/compiled.php(1478): Illuminate\Foundation\Application->make('xe.presenter')
#4 /www_root/bootstrap/cache/compiled.php(6063): Illuminate\Container\Container->offsetGet('xe.presenter')
#5 /www_root/bootstrap/cache/compiled.php(6049): Illuminate\Support\Facades\Facade::resolveFacadeInstance('xe.presenter')
#6 /www_root/bootstrap/cache/compiled.php(6083): Illuminate\Support\Facades\Facade::getFacadeRoot()
#7 /www_root/app/Exceptions/Handler.php(151): Illuminate\Support\Facades\Facade::__callStatic('setSkinTargetId', Array)
#8 /www_root/bootstrap/cache/comp in /www_root/bootstrap/cache/compiled.php:1291
Stack trace:
#0 {main}  
[2018-02-07 10:27:01] production.ERROR: PDOException: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) in /www_root/app/Console/Commands/XeInstall.php:426
Stack trace:
#0 /www_root/app/Console/Commands/XeInstall.php(426): PDO->__construct('mysql:host=loca...', '...', '..., Array)
#1 /www_root/app/Console/Commands/XeInstall.php(272): App\Console\Commands\XeInstall->validateDBInfo(Array)
#2 /www_root/app/Console/Commands/XeInstall.php(199): App\Console\Commands\XeInstall->stepDB()
#3 /www_root/app/Console/Commands/XeInstall.php(138): App\Console\Commands\XeInstall->process()
#4 [internal function]: App\Console\Commands\XeInstall->handle()
#5 /www_root/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#6 /www_root/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#7 /www_root/vendor/symfony/console/Command/Command.php(263): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#8 /www_root/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#9 /www_root/vendor/symfony/console/Application.php(858): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#10 /www_root/vendor/symfony/console/Application.php(205): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\XeInstall), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#11 /www_root/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#12 /www_root/vendor/laravel/framework/src/Illuminate/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#13 /www_root/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(159): Illuminate\Console\Application->call('xe:install', Object(Illuminate\Support\Collection))
#14 /www_root/bootstrap/cache/compiled.php(6093): Illuminate\Foundation\Console\Kernel->call('xe:install', Array)
#15 /www_root/app/Http/Controllers/InstallController.php(82): Illuminate\Support\Facades\Facade::__callStatic('call', Array)
#16 [internal function]: App\Http\Controllers\InstallController->install(Object(Xpressengine\Http\Request), Object(Illuminate\Cookie\CookieJar))
#17 /www_root/bootstrap/cache/compiled.php(8937): call_user_func_array(Array, Array)
#18 /www_root/bootstrap/cache/compiled.php(9006): Illuminate\Routing\Controller->callAction('install', Array)
#19 /www_root/bootstrap/cache/compiled.php(8986): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\InstallController), Object(Illuminate\Routing\Route), 'install')
#20 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Xpressengine\Http\Request))
#21 /www_root/bootstrap/cache/compiled.php(9657): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#23 /www_root/bootstrap/cache/compiled.php(9639): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#24 /www_root/bootstrap/cache/compiled.php(8987): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 /www_root/bootstrap/cache/compiled.php(8972): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\InstallController), Object(Illuminate\Routing\Route), Object(Xpressengine\Http\Request), 'install')
#26 /www_root/bootstrap/cache/compiled.php(7917): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Xpressengine\Http\Request), '\\App\\Http\\Contr...', 'install')
#27 /www_root/bootstrap/cache/compiled.php(7888): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Xpressengine\Http\Request))
#28 /www_root/bootstrap/cache/compiled.php(7541): Illuminate\Routing\Route->run(Object(Xpressengine\Http\Request))
#29 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Xpressengine\Http\Request))
#30 /www_root/bootstrap/cache/compiled.php(9657): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#32 /www_root/bootstrap/cache/compiled.php(9639): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#33 /www_root/bootstrap/cache/compiled.php(7542): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /www_root/bootstrap/cache/compiled.php(7530): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Xpressengine\Http\Request))
#35 /www_root/bootstrap/cache/compiled.php(7515): Illuminate\Routing\Router->dispatchToRoute(Object(Xpressengine\Http\Request))
#36 /www_root/bootstrap/cache/compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Xpressengine\Http\Request))
#37 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Xpressengine\Http\Request))
#38 /www_root/bootstrap/cache/compiled.php(9657): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#39 /www_root/bootstrap/cache/compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#40 /www_root/app/Http/Middleware/ExceptAppendableVerifyCsrfToken.php(21): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Xpressengine\Http\Request), Object(Closure))
#41 [internal function]: App\Http\Middleware\ExceptAppendableVerifyCsrfToken->handle(Object(Xpressengine\Http\Request), Object(Closure))
#42 /www_root/bootstrap/cache/compiled.php(9649): call_user_func_array(Array, Array)
#43 /www_root/bootstrap/cache/compiled.php(13008): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#44 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Xpressengine\Http\Request), Object(Closure))
#45 /www_root/bootstrap/cache/compiled.php(9649): call_user_func_array(Array, Array)
#46 /www_root/bootstrap/cache/compiled.php(11600): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#47 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Xpressengine\Http\Request), Object(Closure))
#48 /www_root/bootstrap/cache/compiled.php(9649): call_user_func_array(Array, Array)
#49 /www_root/bootstrap/cache/compiled.php(12745): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#50 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Xpressengine\Http\Request), Object(Closure))
#51 /www_root/bootstrap/cache/compiled.php(9649): call_user_func_array(Array, Array)
#52 /www_root/bootstrap/cache/compiled.php(12682): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#53 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Xpressengine\Http\Request), Object(Closure))
#54 /www_root/bootstrap/cache/compiled.php(9649): call_user_func_array(Array, Array)
#55 /www_root/bootstrap/cache/compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#56 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Xpressengine\Http\Request), Object(Closure))
#57 /www_root/bootstrap/cache/compiled.php(9649): call_user_func_array(Array, Array)
#58 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Xpressengine\Http\Request))
#59 /www_root/bootstrap/cache/compiled.php(9639): call_user_func(Object(Closure), Object(Xpressengine\Http\Request))
#60 /www_root/bootstrap/cache/compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#61 /www_root/bootstrap/cache/compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Xpressengine\Http\Request))
#62 /www_root/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Xpressengine\Http\Request))
#63 {main}  
```

**Comment by jhyeon1010** [comment]
`bootstrap/app.php` 상단에 보면 `__XE_VERSION__` 라는 상수로 버전이 정의 되어있습니다. 확인되는 버전을 알려주시기 바랍니다.

**Comment by centell** [comment]
@jhyeon1010 답이 늦었습니다. `define('__XE_VERSION__', '3.0.0-beta.23');` 라고 되어있어요.

**Comment by jhyeon1010** [comment]
@centell 공홈에 작성된 사용자분과는 다른 문제로 보이네요.
오래된 버전을 설치하고 계십니다. 최신 버전을 다운받아 설치해보시기 바랍니다.
공홈 사용자분의 경우는 압축파일형태로 제공되는 소스가 빌드될때의 환경이 php7.1 이고 사용환경이 7.0 이어서 발생한 문제로 생각됩니다. 현재는 빌드 환경도 7.0 으로 설정처리 되었습니다.
최신 릴리즈 파일은 [여기](http://start.xpressengine.io/download/latest.zip) 를 클릭하면 다운받을 수 있습니다.

**Comment by centell** [comment]
@jhyeon1010 답변 감사드립니다.
