### ISSUE TITLE
Uncaught Error: Class 'Event' not found

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xpressengine#942]
```
[Thu Feb 07 03:32:15.181907 2019] [:error] [pid 4732] [client 192.168.0.1:4411] PHP Fatal error:  Uncaught Error: Class 'Event' not found in /var/www/xe3/app/Exceptions/Handler.php:100
Stack trace:
#0 /var/www/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): App\\Exceptions\\Handler->render(Object(Xpressengine\\Http\\Request), Object(UnexpectedValueException))
#1 /var/www/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(UnexpectedValueException))
#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(UnexpectedValueException))
#3 {main}
  thrown in /var/www/xe3/app/Exceptions/Handler.php on line 100
[Thu Feb 07 03:32:15.184634 2019] [:error] [pid 4732] [client 192.168.0.1:4411] PHP Fatal error:  Uncaught Error: Class 'Event' not found in /var/www/xe3/app/Exceptions/Handler.php:100
Stack trace:
#0 /var/www/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): App\\Exceptions\\Handler->render(Object(Xpressengine\\Http\\Request), Object(UnexpectedValueException))
#1 /var/www/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(UnexpectedValueException))
#2 /var/www/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(UnexpectedValueException))
#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()
#4 {main}
  thrown in /var/www/xe3/app/Exceptions/Handler.php on line 100
```

배너/Simplestrap 플러그인 설치후 문제가 발생합니다.
아파치 버전은 `Apache/2.4.25 (Raspbian)`이며 php 버전은 `7.0.33-0+deb9u1`입니다.

**Comment by akasima** [comment]
배너 플러그인은 최근에도 사용하고 있어서, 배너 플러그인 문제는 아닐 것 같고..
Simplestrap 플러그인 문제일 것 같습니다.

**Comment by Kazto-lsk** [comment]
안녕하세요,
해당 문제를 해결하기 위해서 CentOS 7 / PHP 7.0 / Apache 2.4.25를 통해 진행하였는데요,
현 테스트 서버 및 테스트 머신에서는 크나큰 문제는 없었습니다.

운영중인 또는 해당 이슈가 발현된 서비스의 OS 및 정보를 조금 더 자세히 부탁드려도 괜찮을까요?
항상 XE에 관심을 가져주셔서 감사합니다.

**Comment by YJSoft** [comment]
```
sudo chmod -Rf 0777 ./storage/
sudo chmod -Rf 0777 ./bootstrap/cache/
```
으로 권한을 강제로 777로 바꾸니 동작합니다. 아마 퍼미션 문제였던것 같습니다.

**Comment by Kazto-lsk** [comment]
@YJSoft 이슈 해결에 도와주셔서 감사합니다.

해당 이슈 이외에는 큰 문제가 없으실까요? 해당 퍼미션 변경이후 생기는 문제들은 없는지 조금 조심스러운데요.
없다면 다행일것 같습니다.

**Comment by YJSoft** [comment]
파일 편집 문제 때문에 파일 소유권을 `pi:www-data`로 해뒀더니 그룹 권한이 없어 문제가 발생한 것으로 보입니다. 이외 다른 문제는 현재까지 없습니다.

**Comment by Kazto-lsk** [comment]
3일이 경과된 현재로써는 추가 이슈가 없는 것으로 보이기에, 본 이슈는 닫겠습니다.
감사합니다.
